# Generated by Django 5.2.2 on 2025-06-21 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Axcontrolmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Axdrivemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Carmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Enginemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Serviceorg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Transmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnumber', models.CharField(blank=True, unique=True, verbose_name='Зав. № машины')),
                ('enginenumber', models.CharField(blank=True, verbose_name='Зав. № двигателя')),
                ('transnember', models.CharField(blank=True, verbose_name='Зав. № трансмиссии')),
                ('axdrivenumber', models.CharField(blank=True, verbose_name='Зав. № ведущего моста')),
                ('axcontrolnumber', models.CharField(blank=True, verbose_name='Зав. № управляемого моста')),
                ('dataconractsupply', models.CharField(blank=True, verbose_name='Договор поставки №, дата')),
                ('datashipfactory', models.DateTimeField(blank=True, null=True, verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(blank=True, verbose_name='Грузополучатель (конечный потребитель)')),
                ('deliveryadd', models.CharField(blank=True, verbose_name='Адрес поставки (эксплуатации)')),
                ('equipment', models.CharField(blank=True, verbose_name='Комплектация (доп. опции)')),
                ('axcontrolmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='axcontrolmodels', to='car.axcontrolmodel', verbose_name='Модель управляемого моста')),
                ('axdrivemodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='axdrivemodels', to='car.axdrivemodel', verbose_name='Модель ведущего моста')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('carmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carmodels', to='car.carmodel', verbose_name='Модель техники')),
                ('enginemodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enginemodels', to='car.enginemodel', verbose_name='Модель двигателя')),
                ('servicecompany', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='car.serviceorg', verbose_name='Сервисная компания')),
                ('transmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmodels', to='car.transmodel', verbose_name='Модель трансмиссии')),
            ],
        ),
    ]
