# Generated by Django 5.2.2 on 2025-06-21 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Failnode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Recoverymethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datamainten', models.DateTimeField(verbose_name='Дата проведения ТО')),
                ('workhour', models.IntegerField(verbose_name='Наработка, м/час')),
                ('workordernum', models.TextField(verbose_name='№ заказ-наряда')),
                ('workorderdate', models.DateTimeField(verbose_name='Дата заказ-наряда')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carsmain', to='car.car', verbose_name='Машина')),
                ('maintenorg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenorgs', to='car.serviceorg', verbose_name='Организация, проводившая ТО')),
                ('serviceorg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serviceorgs', to='car.serviceorg', verbose_name='Сервисная компания')),
                ('viewmainten', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenviews', to='maintenance.maintenview', verbose_name='Вид ТО')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('databroke', models.DateTimeField(verbose_name='Дата отказа')),
                ('workhour', models.IntegerField(verbose_name='Наработка, м/час')),
                ('description', models.TextField(verbose_name='Описание отказа')),
                ('usepart', models.TextField(verbose_name='Используемые запасные части')),
                ('datamainten', models.DateTimeField(verbose_name='Дата проведения ТО')),
                ('restoredate', models.DateTimeField(verbose_name='Дата восстановления')),
                ('downtime', models.DurationField(blank=True, null=True, verbose_name='Время простоя техники')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carcom', to='car.car', verbose_name='Mашина')),
                ('serviceorg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicecom', to='car.serviceorg', verbose_name='Сервисная компания')),
                ('failnode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failnodes', to='maintenance.failnode', verbose_name='Узел отказа')),
                ('recoverymethod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recoverymethods', to='maintenance.recoverymethod', verbose_name='Способ восстановления')),
            ],
        ),
    ]
