# Generated by Django 5.2.2 on 2025-06-26 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_servicecompany_alter_car_user'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carcom', to='car.car', verbose_name='Mашина'),
        ),
    ]
